spring:
  datasource:
    jndi-name: java:comp/env/jdbc/bible-memory
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  thymeleaf:
    encoding: UTF-8
    cache: false
  web:
    resources:
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

ocr:
  google:
    api-key: AIzaSyBG8J_kJUksm2uEfyIXck4HkB1E5Z7uqf8
